const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const seed={clients:[['C001','Green Fields Agro','0722 481 199','Poultry supplies','Active'],['C002','Kisii Fresh Foods','0714 208 551','Retail account','Active'],['C003','Lakeview School','0790 115 226','Egg delivery','Pending'],['C004','BrightCare Clinic','0708 440 904','Monthly supply','Active']],payments:[['P001','Green Fields Agro',28500,'M-Pesa','Paid','2026-06-11'],['P002','Kisii Fresh Foods',12300,'Bank','Paid','2026-06-14'],['P003','Lakeview School',17600,'Cash','Pending','2026-06-16']],invoices:[['INV-1001','Green Fields Agro',28500,'Paid'],['INV-1002','Lakeview School',17600,'Due'],['INV-1003','BrightCare Clinic',40800,'Draft']],services:[['Poultry supply contract','Green Fields Agro','Monthly','Active'],['Egg delivery','Lakeview School','Weekly','Pending'],['Consulting package','BrightCare Clinic','Quarterly','Active']],tasks:[['Call clients with due invoices','Today','High'],['Prepare weekly egg delivery schedule','Tomorrow','Medium'],['Update VAT records','Friday','High']],fund:[['Growth fund reserve',8200],['Community support',2500],['Training & branding',4100]]};
let data=JSON.parse(localStorage.getItem('ngClientBase')||'null')||seed;let page='dashboard';
function save(){localStorage.setItem('ngClientBase',JSON.stringify(data))}function money(n){return 'KSh '+Number(n||0).toLocaleString()}function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2300)}function setPage(p){page=p;$$('nav button,.mobile-tab button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#pageCrumb').textContent=p[0].toUpperCase()+p.slice(1);render(); if(innerWidth<980)$('#sidebar').classList.remove('open')}
function layout(title,body,action=''){return `<div class="section-title"><div><h2>${title}</h2><p class="muted">Professional web-based client management for NextGen operations.</p></div>${action}</div>${body}<div class="footer-note">NextGen Client Base · Professional business dashboard · Contact Rashid Designs 0722481199</div>`}
function render(){updateBadges(); const map={dashboard,clients,payments,invoices,services,tasks,reminders,tithe,vat,integrations,reports,settings};$('#content').innerHTML=map[page]();}
function dashboard(){let total=data.payments.reduce((s,p)=>s+Number(p[2]||0),0), due=data.invoices.filter(i=>i[3]!='Paid').length;return `<div class="hero"><div class="hero-card"><span class="pill">NextGen Client Base</span><h1>ClientBase Pro redesigned for a cleaner NextGen business workflow.</h1><p>Track clients, payments, invoices, recurring services, reminders, VAT and growth fund records in one phone-friendly web app.</p><div class="hero-actions"><button class="btn gold" onclick="openClientForm()">+ Add Client</button><button class="btn light" onclick="setPage('invoices')">Create Invoice</button><button class="btn ghost" onclick="exportData()">Export Backup</button></div></div><div class="card"><h3>Today’s command centre</h3><div class="kpi-ring"><div>76%<br><small class="muted">Healthy</small></div></div><p class="muted">Automated badges show invoices due and upcoming reminders.</p></div></div><div class="stats"><div class="stat"><span>Clients</span><strong>${data.clients.length}</strong></div><div class="stat"><span>Payments</span><strong>${money(total)}</strong></div><div class="stat"><span>Invoices due</span><strong>${due}</strong></div><div class="stat"><span>Active services</span><strong>${data.services.filter(s=>s[3]=='Active').length}</strong></div></div><div class="grid"><div class="card col-8"><div class="section-title"><h3>Recent clients</h3><button class="btn ghost" onclick="setPage('clients')">View all</button></div>${clientCards(data.clients.slice(0,4))}</div><div class="card col-4"><h3>Priority tasks</h3><div class="mini-list">${data.tasks.map(t=>`<div class="mini-row"><span>${t[0]}<br><small class="muted">${t[1]}</small></span><b class="pill ${t[2]=='High'?'red':'warn'}">${t[2]}</b></div>`).join('')}</div></div><div class="card col-12"><h3>Business health</h3><div class="progress"><i style="width:76%"></i></div><p class="muted">Improved dashboard inspired by the reference layout, with a greener NextGen professional brand.</p></div></div>`}
function clientCards(arr){return `<div class="cards">${arr.map(c=>`<div class="client-card"><h3>${c[1]}</h3><p class="muted">${c[3]}</p><p><b>${c[2]}</b></p><span class="pill">${c[4]}</span></div>`).join('')}</div>`}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function clients(){return layout('Clients', clientCards(data.clients)+table(['ID','Client','Phone','Service','Status'],data.clients),`<button class="btn" onclick="openClientForm()">+ Add Client</button>`)}
function payments(){return layout('Payments', table(['Ref','Client','Amount','Method','Status','Date'],data.payments.map(p=>[p[0],p[1],money(p[2]),p[3],`<span class="pill ${p[4]=='Pending'?'warn':''}">${p[4]}</span>`,p[5]])),`<button class="btn" onclick="openPaymentForm()">+ Record Payment</button>`)}
function invoices(){return layout('Invoices', `<div class="cards">${data.invoices.map(i=>`<div class="invoice-paper"><h3>${i[0]}</h3><p class="muted">Bill to ${i[1]}</p><h2>${money(i[2])}</h2><span class="pill ${i[3]=='Due'?'red':i[3]=='Draft'?'warn':''}">${i[3]}</span><p><button class="btn ghost" onclick="window.print()">Print / PDF</button></p></div>`).join('')}</div>`, `<button class="btn" onclick="openInvoiceForm()">+ New Invoice</button>`)}
function services(){return layout('Current Services', table(['Service','Client','Cycle','Status'],data.services.map(s=>[s[0],s[1],s[2],`<span class="pill">${s[3]}</span>`])),`<button class="btn" onclick="openServiceForm()">+ Add Service</button>`)}
function tasks(){return layout('Recurrent Services', table(['Task','Due','Priority'],data.tasks.map(t=>[t[0],t[1],`<span class="pill ${t[2]=='High'?'red':'warn'}">${t[2]}</span>`])),`<button class="btn" onclick="openTaskForm()">+ Add Task</button>`)}
function reminders(){return layout('Reminders', `<div class="mini-list">${data.tasks.map(t=>`<div class="mini-row"><b>🔔 ${t[0]}</b><span class="pill">${t[1]}</span></div>`).join('')}</div>`)}
function tithe(){return layout('Growth Fund', table(['Category','Amount'],data.fund.map(f=>[f[0],money(f[1])]))+`<div class="card" style="margin-top:16px"><h3>Total reserve: ${money(data.fund.reduce((s,f)=>s+f[1],0))}</h3></div>`)}
function vat(){let vat=data.payments.reduce((s,p)=>s+p[2]*0.16,0);return layout('VAT Tracker', `<div class="stats"><div class="stat"><span>Taxable sales</span><strong>${money(data.payments.reduce((s,p)=>s+p[2],0))}</strong></div><div class="stat"><span>Estimated VAT 16%</span><strong>${money(vat)}</strong></div></div>${table(['Client','Amount','VAT Estimate'],data.payments.map(p=>[p[1],money(p[2]),money(p[2]*.16)]))}`)}
function integrations(){return layout('M-Pesa & Bank Automatic Updates', `<div class="hero"><div class="hero-card"><span class="pill">Integration-ready</span><h1>Connect M-Pesa and bank payments to update records automatically.</h1><p>This static GitHub Pages front-end is now prepared for payment automation. Live automatic updates need a small secure backend because Safaricom Daraja and bank APIs require private keys, callback URLs and server-side verification.</p><div class="hero-actions"><button class="btn gold" onclick="openPaymentForm()">Test Manual Payment</button><button class="btn light" onclick="downloadIntegrationPlan()">Download Setup Plan</button></div></div><div class="card"><h3>Connection status</h3><div class="mini-list"><div class="mini-row"><b>M-Pesa Daraja</b><span class="pill warn">Needs credentials</span></div><div class="mini-row"><b>Bank API / statement import</b><span class="pill warn">Needs bank access</span></div><div class="mini-row"><b>Auto-match to invoices</b><span class="pill">Ready in app</span></div></div></div></div><div class="grid"><div class="card col-6"><h3>M-Pesa automation</h3><p class="muted">Recommended production flow:</p><div class="mini-list"><div class="mini-row"><span>1. Register Paybill/Till with Daraja</span><b>Safaricom</b></div><div class="mini-row"><span>2. Backend receives C2B/STK callbacks</span><b>Server</b></div><div class="mini-row"><span>3. Match phone/reference/invoice number</span><b>Auto</b></div><div class="mini-row"><span>4. Mark invoice Paid and add payment</span><b>Live</b></div></div></div><div class="card col-6"><h3>Bank automation</h3><p class="muted">Most Kenyan banks need business internet banking/API access, emailed statements or CSV import. This app can accept a bank feed once the bank provides a safe integration method.</p><div class="mini-list"><div class="mini-row"><span>CSV/Excel statement import</span><span class="pill">Fastest</span></div><div class="mini-row"><span>Official bank API</span><span class="pill warn">Bank approval</span></div><div class="mini-row"><span>SMS/email parsing</span><span class="pill warn">Backend needed</span></div></div></div><div class="card col-12"><h3>What I need from you for real live integration</h3>${table(['Provider','Required details'],[['M-Pesa','Business Paybill/Till, Daraja Consumer Key/Secret, shortcode, passkey, callback URL approval'],['Bank','Bank name, account type, available API/statement export method, test credentials if available'],['Hosting','A backend host such as Render, Railway, VPS, cPanel Node/PHP, or Firebase/Cloud Functions']])}</div></div>`)}
function reports(){return layout('Reports & Exports', `<div class="cards"><div class="card"><h3>Backup data</h3><p class="muted">Download JSON backup for safe keeping.</p><button class="btn" onclick="exportData()">Download JSON</button></div><div class="card"><h3>Print report</h3><p class="muted">Use browser print to PDF for professional reports.</p><button class="btn ghost" onclick="window.print()">Print / Save PDF</button></div><div class="card"><h3>Reset demo</h3><p class="muted">Restore sample NextGen records.</p><button class="btn ghost" onclick="resetDemo()">Reset Demo</button></div></div>`)}
function settings(){return layout('Settings', `<div class="card"><h3>Business profile</h3><div class="form-grid"><div class="field"><label>Business name</label><input value="NextGen Client Base"></div><div class="field"><label>Contact</label><input value="0722 481 199"></div><div class="field"><label>Owner / Admin</label><input value="Rashid Designs"></div><div class="field"><label>Brand style</label><input value="Professional Green + Gold"></div></div></div>`)}
function modal(html){$('#modal').innerHTML=`<div class="modal-box">${html}</div>`;$('#modal').style.display='grid'}function closeModal(){$('#modal').style.display='none'}
function openClientForm(){modal(`<h2>Add client</h2><div class="form-grid"><div class="field"><label>Name</label><input id="fName"></div><div class="field"><label>Phone</label><input id="fPhone"></div><div class="field"><label>Service</label><input id="fSvc"></div><div class="field"><label>Status</label><select id="fStatus"><option>Active</option><option>Pending</option></select></div></div><p><button class="btn" onclick="addClient()">Save Client</button> <button class="btn ghost" onclick="closeModal()">Cancel</button></p>`)}
function addClient(){data.clients.push(['C'+String(data.clients.length+1).padStart(3,'0'),$('#fName').value||'New Client',$('#fPhone').value||'0700000000',$('#fSvc').value||'General service',$('#fStatus').value]);save();closeModal();render();toast('Client saved')}
function openPaymentForm(){modal(`<h2>Record payment</h2><div class="form-grid"><div class="field"><label>Client</label><input id="pClient"></div><div class="field"><label>Amount</label><input id="pAmt" type="number"></div><div class="field"><label>Method</label><select id="pMethod"><option>M-Pesa</option><option>Cash</option><option>Bank</option></select></div><div class="field"><label>Status</label><select id="pStatus"><option>Paid</option><option>Pending</option></select></div></div><p><button class="btn" onclick="addPayment()">Save Payment</button> <button class="btn ghost" onclick="closeModal()">Cancel</button></p>`)}
function addPayment(){data.payments.push(['P'+String(data.payments.length+1).padStart(3,'0'),$('#pClient').value||'Walk-in Client',Number($('#pAmt').value||0),$('#pMethod').value,$('#pStatus').value,new Date().toISOString().slice(0,10)]);save();closeModal();render();toast('Payment recorded')}
function openInvoiceForm(){modal(`<h2>New invoice</h2><div class="form-grid"><div class="field"><label>Client</label><input id="iClient"></div><div class="field"><label>Amount</label><input id="iAmt" type="number"></div><div class="field"><label>Status</label><select id="iStatus"><option>Due</option><option>Draft</option><option>Paid</option></select></div></div><p><button class="btn" onclick="addInvoice()">Save Invoice</button> <button class="btn ghost" onclick="closeModal()">Cancel</button></p>`)}
function addInvoice(){data.invoices.push(['INV-'+(1001+data.invoices.length),$('#iClient').value||'Client',Number($('#iAmt').value||0),$('#iStatus').value]);save();closeModal();render();toast('Invoice created')}
function openServiceForm(){modal(`<h2>Add service</h2><div class="form-grid"><div class="field"><label>Service</label><input id="sName"></div><div class="field"><label>Client</label><input id="sClient"></div><div class="field"><label>Cycle</label><input id="sCycle" value="Monthly"></div><div class="field"><label>Status</label><select id="sStatus"><option>Active</option><option>Pending</option></select></div></div><p><button class="btn" onclick="addService()">Save Service</button> <button class="btn ghost" onclick="closeModal()">Cancel</button></p>`)}
function addService(){data.services.push([$('#sName').value||'New Service',$('#sClient').value||'Client',$('#sCycle').value,$('#sStatus').value]);save();closeModal();render();toast('Service added')}
function openTaskForm(){modal(`<h2>Add recurrent task</h2><div class="form-grid"><div class="field"><label>Task</label><input id="tName"></div><div class="field"><label>Due</label><input id="tDue" value="Today"></div><div class="field"><label>Priority</label><select id="tPr"><option>High</option><option>Medium</option></select></div></div><p><button class="btn" onclick="addTask()">Save Task</button> <button class="btn ghost" onclick="closeModal()">Cancel</button></p>`)}
function addTask(){data.tasks.push([$('#tName').value||'Follow up client',$('#tDue').value||'Today',$('#tPr').value]);save();closeModal();render();toast('Task added')}
function updateBadges(){let inv=data.invoices.filter(i=>i[3]=='Due').length, rem=data.tasks.length;[['#invoiceBadge',inv],['#reminderBadge',rem],['#notifCount',inv+rem]].forEach(([s,n])=>{let e=$(s); if(e){e.style.display=n?'grid':'none';e.textContent=n}})}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='nextgen-client-base-backup.json';a.click();toast('Backup downloaded')}
function downloadIntegrationPlan(){let text=`NextGen Client Base - M-Pesa and Bank Automatic Updates Setup\n\nLive automatic updates require a secure backend, not only GitHub Pages.\n\nM-Pesa Daraja requirements:\n- Safaricom developer app Consumer Key and Consumer Secret\n- Paybill/Till shortcode\n- STK Push passkey or C2B confirmation/validation setup\n- Public HTTPS callback URL\n- Backend to verify transaction callbacks and update invoices/payments\n\nBank requirements:\n- Bank name and account type\n- Official API access, statement export, or CSV/Excel format\n- Secure import/matching logic by invoice number, phone, account name or reference\n\nRecommended next build:\n1. Add Node/PHP backend with database.\n2. Add /api/mpesa/callback endpoint.\n3. Add /api/bank/import or bank webhook.\n4. Store payments in database and sync dashboard.\n5. Keep all secrets on server only. Never put keys in browser JavaScript.\n`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='nextgen-payment-integration-plan.txt';a.click();toast('Integration plan downloaded')}
function resetDemo(){localStorage.removeItem('ngClientBase');data=JSON.parse(JSON.stringify(seed));save();render();toast('Demo data restored')}
$('#nav').addEventListener('click',e=>{let b=e.target.closest('button[data-page]');if(b)setPage(b.dataset.page)});$('#menuBtn').onclick=()=>$('#sidebar').classList.add('open');$('#collapseBtn').onclick=()=>$('#sidebar').classList.toggle('collapsed');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#globalSearch').oninput=e=>{let q=e.target.value.toLowerCase().trim(), box=$('#searchResults'); if(!q){box.style.display='none';return}let all=[...data.clients.map(c=>['clients',c[1],c[3]]),...data.invoices.map(i=>['invoices',i[0],i[1]]),...data.payments.map(p=>['payments',p[1],money(p[2])])].filter(x=>x.join(' ').toLowerCase().includes(q)).slice(0,6);box.innerHTML=all.map(x=>`<button onclick="setPage('${x[0]}');$('#searchResults').style.display='none'">${x[1]}<br><small>${x[2]}</small></button>`).join('')||'<button>No result found</button>';box.style.display='block'};
function mobile(){let items=[['dashboard','▣<br>Home'],['clients','👥<br>Clients'],['payments','💳<br>Pay'],['invoices','🧾<br>Inv'],['settings','⚙️<br>More']];$('#mobileTab').innerHTML=items.map(i=>`<button data-page="${i[0]}" onclick="setPage('${i[0]}')">${i[1]}</button>`).join('')}
setInterval(()=>$('#timeNow').textContent=new Date().toLocaleString([], {hour:'2-digit',minute:'2-digit',weekday:'short'}),1000);mobile();render();